version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    working_directory: ~/build
    docker:
      - image: cimg/python:latest  # Use a base image with find and other utilities
    resource_class: small
    steps:
      - run:
          name: Install Sonar Scanner
          command: |
             sudo install apt-get
            curl -sSLo /tmp/sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip /tmp/sonar-scanner.zip -d /opt
            export PATH=$PATH:/opt/sonar-scanner-4.7.0.2747-linux/bin
      - run:
          name: "Find Files"
          command: find .
      - attach_workspace:
          at: ~/workspace
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
