version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout  # Ensure the code is available in this job
      - attach_workspace:
          at: ./workspace  # Attach the workspace to a custom directory
      - run:
          name: "Install findutils and Java 17"
          command: |
            sudo apt-get update && \
            sudo apt-get install -y findutils openjdk-17-jdk wget  # Install find, Java 17, and wget
            # Download and install SonarScanner
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -O sonar-scanner.zip
            unzip sonar-scanner.zip
            sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
            # Set Java 17 as the default
            sudo update-alternatives --config java
            java -version  # Verify that Java 17 is being used
      - run:
          name: "Find files"
          command: "find ./workspace"  # Search in the attached workspace directory
      - run:
          name: "Run SonarQube scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is : $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="./workspace"  # Use the correct directory for sources

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello  # Ensure that 'sonarqube' runs after 'say-hello'
