version: 2.1

jobs:
  sonarqube:
    docker:
      - image: cimg/openjdk:17.0  # Use the Java 17 Docker image
    steps:
      - checkout
      - run:
          name: "Verify Java version"
          command: |
            java -version
            javac -version
      - run:
          name: "Install SonarScanner"
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -O sonar-scanner.zip
            unzip sonar-scanner.zip
            sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
            
      - run:
          name: "Run SonarQube scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is : $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  sonar-workflow:
    jobs:
      - sonarqube
