version: 2.1

jobs:
  sonarqube:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Find Java 17 installation"
          command: |
            echo "Available Java versions:"
            ls -l /usr/lib/jvm/
            
            # Find Java 17 installation
            JAVA_17_PATH=$(find /usr/lib/jvm -name "java" | grep "openjdk-17")
            echo "Java 17 path: $JAVA_17_PATH"
            
            # Set JAVA_HOME
            export JAVA_HOME=$(dirname $(dirname $JAVA_17_PATH))
            echo "JAVA_HOME set to: $JAVA_HOME"
            
            # Update PATH
            export PATH=$JAVA_HOME/bin:$PATH
            
            # Verify Java version
            java -version
            
      - run:
          name: "Install SonarScanner"
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -O sonar-scanner.zip
            unzip sonar-scanner.zip
            sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
            
      - run:
          name: "Run SonarQube scanner with Java 17"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is : $SONAR_BRANCH"
            
            # Run SonarScanner using the located Java 17 binary
            $JAVA_17_PATH -jar /opt/sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  sonar-workflow:
    jobs:
      - sonarqube
