version: 2.1

jobs:
  sonarqube:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: "Find Java installation"
          command: |
            echo "Available Java versions:"
            java --version
            
            # Find Java executable
            JAVA_PATH=$(command -v java)
            echo "Java path: $JAVA_PATH"
            
            # Set JAVA_HOME
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            echo "JAVA_HOME set to: $JAVA_HOME"
            
            # Update PATH
            export PATH=$JAVA_HOME/bin:$PATH
            
            # Verify Java version again
            java --version
            
      - run:
          name: "Install SonarScanner"
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -O sonar-scanner.zip
            unzip sonar-scanner.zip
            ls -l sonar-scanner-4.8.0.2856-linux
            sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
            sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
            
            # Verify the integrity of the SonarScanner directory
            ls -R /opt/sonar-scanner
            
      - run:
          name: "Run SonarQube scanner"
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is : $SONAR_BRANCH"
            
            # Check if Java executable exists
            if [ ! -x "$JAVA_HOME/bin/java" ]; then
              echo "Error: Java executable not found at $JAVA_HOME/bin/java"
              exit 1
            fi
            
            # Check if SonarScanner JAR exists
            if [ ! -f "/opt/sonar-scanner/bin/sonar-scanner" ]; then
              echo "Error: SonarScanner JAR not found at /opt/sonar-scanner/bin/sonar-scanner"
              exit 1
            fi
            
            # Run SonarScanner
            "$JAVA_HOME/bin/java" -jar "/opt/sonar-scanner/bin/sonar-scanner" \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  sonar-workflow:
    jobs:
      - sonarqube
